"""Regression suite for install.sh / install.ps1 (ROADMAP item 1, Phase 11).

Runs both installer scripts against real temporary target directories via
subprocess, exercising the same on-disk contract their own --help/synopsis
promises: copy the skill set (.github/skills/, .github/prompts/,
.cursor/rules/, AGENTS.md as a marked block) into --target/-TargetPath, and
under --init-project/-InitProject additionally scaffold context-config.yaml
and starter_kit/project_guidelines/.pointer.md. Also covers two later
additions with the same on-disk-contract framing: bundling CEP's own docs
(CONCEPT.md/PROTOCOL.md/README.md/FAQ.md/case-studies/) into
.github/skills/ult-cep-wizard/docs/ so wizard_docs.py has something to serve
in a real install, and writing .cep-install.json recording what the
installer itself just put on disk (see cep_retrofit.py/discover_layers.py/
scaffold_state.py's own manifest-consumer docstrings for why that fact
matters downstream). Also covers --runtime/-Runtime claude|copilot|cursor|codex|both, which
scopes which of .github/prompts/, .cursor/rules/, and an AGENTS.md merge
come along beside .github/skills/ (always copied, every value) - claude:
skills only; copilot: skills + prompts; cursor: skills + prompts + rules;
codex: skills + AGENTS.md; both: everything (default, unchanged when the
flag is omitted).

Reuses generated_config_text() from test_generated_context_config.py rather
than re-deriving the substitution table a third time (install.sh and
install.ps1 each hardcode it once; this test is the independent witness that
both match the template).

Requires bash and one of {pwsh, powershell} on PATH; each installer's test
class is skipped (not failed) if its interpreter isn't available locally -
CI (ubuntu-latest) has both.

    python -m unittest discover -s scripts/tests -v
"""

import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from test_generated_context_config import generated_config_text  # noqa: E402

# .github/skills/ult-repo-layout/scripts/tests/ -> repo root
REPO_ROOT = Path(__file__).resolve().parents[5]
INSTALL_SH = REPO_ROOT / "install.sh"
INSTALL_PS1 = REPO_ROOT / "install.ps1"

LIBRARY_DIRS = [
    ".github/skills",
    ".github/prompts",
    ".cursor/rules",
]

# See Copy-CepWizardDocs (install.ps1) / copy_cep_wizard_docs (install.sh):
# both installers bundle CEP's own repo-root docs into this path, sibling to
# the ult-cep-wizard skill itself, so wizard_docs.py has something to serve
# in a real install. It is NOT part of the .github/skills source tree (its
# content comes from repo-root files, composed at install time), so
# test_plain_install_copies_library excludes it from the strict
# .github/skills tree-match and _assert_cep_wizard_docs_bundle checks it
# separately instead.
DOCS_BUNDLE_REL = "ult-cep-wizard/docs"
DOCS_BUNDLE_SOURCE_FILES = ["CONCEPT.md", "PROTOCOL.md", "README.md", "FAQ.md"]
DOCS_BUNDLE_SOURCE_DIRNAME = "case-studies"

BEGIN_MARKER = "<!-- BEGIN context-engineering-protocol SKILLS (auto-generated, do not edit) -->"
END_MARKER = "<!-- END context-engineering-protocol SKILLS -->"

POINTER_TEXT = """# project_guidelines — starter-kit drop-zone

This directory holds project-owned, human-curated material for `project_guidelines`.
Current template and README: `starter_kits/project_guidelines/` in the
skills library this project pulls from.

This file is regenerated by the installer's -InitProject/--init-project mode
and by `/ult-repo-layout init`/`reconcile` — do not edit it directly. Place
your own files alongside it; they are never touched.
"""



# Gitignored local build artifacts (see repo .gitignore) that may exist in
# this checkout's working tree if tests were ever run here. Both installers
# now exclude these when copying (never leak into an installed target
# project), so the source side of the comparison must ignore them too -
# otherwise this test just re-encodes the leak as "correct" behavior.
_IGNORED_DIR_NAMES = {"__pycache__", ".pytest_cache"}


def _tree_files(root: Path, ignore_prefixes=()):
    files = set()
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in _IGNORED_DIR_NAMES]
        for name in filenames:
            if name.endswith(".pyc"):
                continue
            rel = Path(dirpath, name).relative_to(root)
            rel_str = str(rel).replace("\\", "/")
            if any(rel_str == p or rel_str.startswith(p + "/") for p in ignore_prefixes):
                continue
            files.add(rel_str)
    return files


def _assert_tree_matches(test, src: Path, dst: Path, ignore_prefixes=()):
    test.assertTrue(dst.is_dir(), f"missing directory: {dst}")
    src_files = _tree_files(src, ignore_prefixes)
    dst_files = _tree_files(dst, ignore_prefixes)
    test.assertEqual(src_files, dst_files, f"file set mismatch between {src} and {dst}")
    for rel in src_files:
        test.assertEqual(
            (src / rel).read_bytes(),
            (dst / rel).read_bytes(),
            f"content mismatch: {rel}",
        )


def _assert_cep_wizard_docs_bundle(test, target: Path):
    """Asserts the bundled docs/ subtree (see DOCS_BUNDLE_REL) is present
    under the installed ult-cep-wizard skill and byte-identical to its
    repo-root source files."""
    bundle = target / ".github/skills" / DOCS_BUNDLE_REL
    test.assertTrue(bundle.is_dir(), f"missing bundled docs dir: {bundle}")
    for name in DOCS_BUNDLE_SOURCE_FILES:
        test.assertEqual(
            (REPO_ROOT / name).read_bytes(),
            (bundle / name).read_bytes(),
            f"content mismatch: {name}",
        )
    _assert_tree_matches(
        test,
        REPO_ROOT / DOCS_BUNDLE_SOURCE_DIRNAME,
        bundle / DOCS_BUNDLE_SOURCE_DIRNAME,
    )


def _assert_cep_install_manifest(test, target: Path, mode: str, only_skills=None, runtime=None):
    """Asserts .cep-install.json's shape (see New-CepInstallManifest in
    install.ps1 / write_cep_install_manifest in install.sh). `runtime`
    defaults to the "both" value's expansion (["claude", "copilot"]) — pass
    the expected list explicitly for a --runtime/-Runtime claude-only or
    copilot-only run."""
    manifest_path = target / ".cep-install.json"
    test.assertTrue(manifest_path.is_file(), f"missing manifest: {manifest_path}")
    data = json.loads(manifest_path.read_text(encoding="utf-8"))
    test.assertEqual(data.get("schema_version"), 1)
    expected_runtime = ["claude", "copilot"] if runtime is None else runtime
    test.assertEqual(sorted(data.get("runtime") or []), sorted(expected_runtime))
    test.assertEqual(data.get("mode"), mode)
    if only_skills:
        test.assertEqual(sorted(data.get("only_skills") or []), sorted(only_skills))
    else:
        test.assertIsNone(data.get("only_skills"))
    owned = data.get("owned_paths")
    test.assertIsInstance(owned, list)
    test.assertTrue(owned, "owned_paths must not be empty")
    test.assertIn("installed_at", data)
    return data


# Verb vocabulary log_action (install.sh) / Write-InstallAction (install.ps1)
# use for a dry-run line that means "this path would be written" — both
# scripts share the exact wording at every call site (see
# copy_tree/Copy-LibraryTree, merge_agents_md/Merge-AgentsMd,
# scaffold_context_config/New-ContextConfig,
# scaffold_pointer/New-ProjectGuidelinesPointer, and
# write_cep_install_manifest/New-CepInstallManifest). These are the
# dry-run-specific present-tense phrasings ("would create", not "would
# created") — not derivable from the real-run past-tense verbs by just
# prefixing "would ". "would update: ..." (the pointer's existing-file
# dry-run case) is omitted: it only fires when the target already has a
# pointer file, which a fresh temp dir never does.
_DRY_RUN_CREATE_VERBS = {
    "would create",
    "would overwrite",
    "would write",
    "would update block in",
    "would append block to",
}


def _parse_created_paths(transcript: str):
    """Extracts every path a dry-run transcript claims it would write, using
    _DRY_RUN_CREATE_VERBS. Each write site logs exactly one line per
    top-level call — a whole-directory copy (e.g. ".github/skills") is one
    line for the whole subtree, while copy_cep_wizard_docs/Copy-CepWizardDocs
    calls copy_tree/Copy-LibraryTree once per doc file, so it contributes one
    line per file."""
    paths = []
    for line in transcript.splitlines():
        line = line.strip()
        if ": " not in line:
            continue
        verb, _, rest = line.partition(": ")
        if verb in _DRY_RUN_CREATE_VERBS:
            paths.append(rest.strip())
    return paths


def _owned_path_covers(rel: str, owned_paths) -> bool:
    """True iff `rel` exactly matches one of owned_paths, or is a descendant
    of one — mirrors the descendant-aware convention discover_layers.py's
    _manifest_extra_ignored already uses for the same owned_paths list, so a
    directory entry like ".github/skills" covers every file dry-run reports
    under it without each file needing its own owned_paths entry."""
    rel_path = Path(rel)
    for owned in owned_paths:
        owned_path = Path(owned)
        if rel_path == owned_path:
            return True
        try:
            rel_path.relative_to(owned_path)
            return True
        except ValueError:
            continue
    return False


class _InstallScriptTestBase:
    """Shared assertions across both installers; subclasses provide _run()."""

    def _run(self, target, args):
        raise NotImplementedError

    def test_plain_install_copies_library(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [])
            self.assertEqual(result.returncode, 0, result.stderr)
            for rel in LIBRARY_DIRS:
                # .github/skills also gains the bundled ult-cep-wizard/docs/
                # subtree (see DOCS_BUNDLE_REL) - not part of this source
                # tree, so excluded here and checked separately below.
                ignore = (DOCS_BUNDLE_REL,) if rel == ".github/skills" else ()
                _assert_tree_matches(self, REPO_ROOT / rel, target / rel, ignore)
            _assert_cep_wizard_docs_bundle(self, target)
            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn(BEGIN_MARKER, agents)
            self.assertIn(END_MARKER, agents)
            source_agents = (REPO_ROOT / "AGENTS.md").read_text(encoding="utf-8").strip()
            self.assertIn(source_agents, agents)
            self.assertFalse((target / "context-config.yaml").exists())
            self.assertFalse((target / "starter_kit").exists())
            _assert_cep_install_manifest(self, target, mode="full")

    def test_init_project_scaffolds_config_and_pointer(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.init_flag])
            self.assertEqual(result.returncode, 0, result.stderr)
            config_text = (target / "context-config.yaml").read_text(encoding="utf-8")
            self.assertEqual(config_text, generated_config_text())
            pointer_text = (
                target / "starter_kit" / "project_guidelines" / ".pointer.md"
            ).read_text(encoding="utf-8")
            self.assertEqual(pointer_text.strip(), POINTER_TEXT.strip())

    def test_rerun_is_idempotent(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            first = self._run(target, [self.init_flag])
            self.assertEqual(first.returncode, 0, first.stderr)

            # A hand-edited context-config.yaml must survive re-install:
            # it's project-owned, scaffold-once, never library-overwritten.
            (target / "context-config.yaml").write_text("# hand-edited\n", encoding="utf-8")

            second = self._run(target, [self.init_flag])
            self.assertEqual(second.returncode, 0, second.stderr)

            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertEqual(agents.count(BEGIN_MARKER), 1)
            self.assertEqual(
                (target / "context-config.yaml").read_text(encoding="utf-8"),
                "# hand-edited\n",
            )

    def test_dry_run_writes_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.init_flag, self.dry_run_flag])
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(list(target.iterdir()), [])

    def test_missing_target_fails_clearly(self):
        with tempfile.TemporaryDirectory() as tmp:
            missing = Path(tmp) / "does-not-exist"
            result = self._run(missing, [])
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("does not exist", result.stderr + result.stdout)

    def _skill_paths(self, name):
        return [
            f".github/skills/{name}",
            f".github/prompts/{name}.prompt.md",
            f".cursor/rules/{name}.mdc",
        ]

    def test_only_flag_installs_selected_skill_and_skips_others(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.only_flag, "demo-consume-context"])
            self.assertEqual(result.returncode, 0, result.stderr)

            for rel in self._skill_paths("demo-consume-context"):
                self.assertEqual(
                    (target / rel).is_dir(),
                    (REPO_ROOT / rel).is_dir(),
                    f"tree-shape mismatch: {rel}",
                )
            _assert_tree_matches(
                self,
                REPO_ROOT / ".github/skills/demo-consume-context",
                target / ".github/skills/demo-consume-context",
            )
            self.assertEqual(
                (REPO_ROOT / ".github/prompts/demo-consume-context.prompt.md").read_bytes(),
                (target / ".github/prompts/demo-consume-context.prompt.md").read_bytes(),
            )
            self.assertEqual(
                (REPO_ROOT / ".cursor/rules/demo-consume-context.mdc").read_bytes(),
                (target / ".cursor/rules/demo-consume-context.mdc").read_bytes(),
            )

            for rel in self._skill_paths("ult-codegraph"):
                self.assertFalse((target / rel).exists(), f"unselected skill leaked in: {rel}")

            # ult-cep-wizard wasn't selected: no docs bundle at all, not even
            # an empty one - Copy-CepWizardDocs/copy_cep_wizard_docs only run
            # when that name is in the selected set.
            self.assertFalse((target / ".github/skills/ult-cep-wizard").exists())

            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("demo-consume-context", agents)
            self.assertNotIn("ult-codegraph", agents)

            _assert_cep_install_manifest(
                self, target, mode="only", only_skills=["demo-consume-context"]
            )

    def test_only_flag_with_cep_wizard_bundles_docs(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.only_flag, "ult-cep-wizard"])
            self.assertEqual(result.returncode, 0, result.stderr)

            for rel in self._skill_paths("ult-cep-wizard"):
                self.assertTrue((target / rel).exists(), f"missing selected skill path: {rel}")
            _assert_cep_wizard_docs_bundle(self, target)

            data = _assert_cep_install_manifest(
                self, target, mode="only", only_skills=["ult-cep-wizard"]
            )
            self.assertIn(
                f".github/skills/{DOCS_BUNDLE_REL}",
                data["owned_paths"],
            )

    def test_only_flag_supports_multiple_skills(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(
                target, [self.only_flag, "demo-consume-context, ult-codegraph"]
            )
            self.assertEqual(result.returncode, 0, result.stderr)

            for name in ("demo-consume-context", "ult-codegraph"):
                for rel in self._skill_paths(name):
                    self.assertTrue((target / rel).exists(), f"missing selected skill path: {rel}")

            for rel in self._skill_paths("compiling-project-guidelines"):
                self.assertFalse((target / rel).exists(), f"unselected skill leaked in: {rel}")

            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn("demo-consume-context", agents)
            self.assertIn("ult-codegraph", agents)
            self.assertNotIn("compiling-project-guidelines", agents)

            _assert_cep_install_manifest(
                self,
                target,
                mode="only",
                only_skills=["demo-consume-context", "ult-codegraph"],
            )

    def test_only_flag_rejects_unknown_skill_name(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.only_flag, "bogus-skill-name"])
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("bogus-skill-name", result.stderr + result.stdout)

    def test_runtime_claude_installs_skills_tree_only(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.runtime_flag, "claude"])
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((target / ".github/skills").is_dir())
            self.assertFalse((target / ".github/prompts").exists())
            self.assertFalse((target / ".cursor/rules").exists())
            self.assertFalse((target / "AGENTS.md").exists())
            # The bundled ult-cep-wizard docs live under .github/skills/, so
            # they're still copied even though prompts/rules are skipped.
            _assert_cep_wizard_docs_bundle(self, target)
            _assert_cep_install_manifest(self, target, mode="full", runtime=["claude"])

    def test_runtime_copilot_installs_prompts_but_not_cursor_rules(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.runtime_flag, "copilot"])
            self.assertEqual(result.returncode, 0, result.stderr)
            for rel in (".github/skills", ".github/prompts"):
                ignore = (DOCS_BUNDLE_REL,) if rel == ".github/skills" else ()
                _assert_tree_matches(self, REPO_ROOT / rel, target / rel, ignore)
            self.assertFalse((target / ".cursor/rules").exists())
            self.assertFalse((target / "AGENTS.md").exists())
            _assert_cep_install_manifest(self, target, mode="full", runtime=["copilot"])

    def test_runtime_cursor_installs_skills_prompts_and_rules(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.runtime_flag, "cursor"])
            self.assertEqual(result.returncode, 0, result.stderr)
            for rel in LIBRARY_DIRS:
                ignore = (DOCS_BUNDLE_REL,) if rel == ".github/skills" else ()
                _assert_tree_matches(self, REPO_ROOT / rel, target / rel, ignore)
            self.assertFalse((target / "AGENTS.md").exists())
            _assert_cep_install_manifest(self, target, mode="full", runtime=["cursor"])

    def test_runtime_codex_installs_skills_and_agents_md_only(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.runtime_flag, "codex"])
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((target / ".github/skills").is_dir())
            self.assertFalse((target / ".github/prompts").exists())
            self.assertFalse((target / ".cursor/rules").exists())
            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn(BEGIN_MARKER, agents)
            self.assertIn(END_MARKER, agents)
            _assert_cep_wizard_docs_bundle(self, target)
            _assert_cep_install_manifest(self, target, mode="full", runtime=["codex"])

    def test_runtime_both_matches_default_behavior(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.runtime_flag, "both"])
            self.assertEqual(result.returncode, 0, result.stderr)
            for rel in LIBRARY_DIRS:
                ignore = (DOCS_BUNDLE_REL,) if rel == ".github/skills" else ()
                _assert_tree_matches(self, REPO_ROOT / rel, target / rel, ignore)
            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn(BEGIN_MARKER, agents)
            _assert_cep_install_manifest(self, target, mode="full", runtime=["claude", "copilot"])

    def test_runtime_claude_with_only_flag_skips_prompts_and_rules(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(
                target, [self.only_flag, "demo-consume-context", self.runtime_flag, "claude"]
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertTrue((target / ".github/skills/demo-consume-context").is_dir())
            self.assertFalse((target / ".github/prompts/demo-consume-context.prompt.md").exists())
            self.assertFalse((target / ".cursor/rules/demo-consume-context.mdc").exists())
            self.assertFalse((target / "AGENTS.md").exists())
            _assert_cep_install_manifest(
                self,
                target,
                mode="only",
                only_skills=["demo-consume-context"],
                runtime=["claude"],
            )

    def test_runtime_copilot_dry_run_excludes_cursor_and_agents_md(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.runtime_flag, "copilot", self.dry_run_flag])
            self.assertEqual(result.returncode, 0, result.stderr)
            transcript = result.stdout
            self.assertNotIn(".cursor/rules", transcript)
            self.assertNotIn("AGENTS.md", transcript)

    def test_runtime_rejects_unknown_value(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.runtime_flag, "bogus-runtime"])
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("runtime", (result.stderr + result.stdout).lower())

    def _assert_dry_run_paths_covered_by_owned_paths(self, args, mode, **manifest_kwargs):
        """Runs a dry-run and a real install with the same `args` in two
        separate temp dirs, then asserts every path the dry-run transcript
        reports writing is covered (see _owned_path_covers) by the real
        install's .cep-install.json owned_paths. Catches the exact defect
        class this manifest exists to prevent: a write site the installer
        performs but forgets to record as CEP-owned."""
        with tempfile.TemporaryDirectory() as dry_tmp, tempfile.TemporaryDirectory() as real_tmp:
            dry_target = Path(dry_tmp)
            dry_result = self._run(dry_target, [*args, self.dry_run_flag])
            self.assertEqual(dry_result.returncode, 0, dry_result.stderr)
            created = _parse_created_paths(dry_result.stdout)
            self.assertTrue(created, "dry-run transcript reported no writes to check")

            real_target = Path(real_tmp)
            real_result = self._run(real_target, args)
            self.assertEqual(real_result.returncode, 0, real_result.stderr)
            data = _assert_cep_install_manifest(self, real_target, mode=mode, **manifest_kwargs)
            owned_paths = data["owned_paths"]

            for rel in created:
                if rel == ".cep-install.json":
                    # Recorded by construction (write_cep_install_manifest /
                    # New-CepInstallManifest appends its own path before
                    # serializing) — checked directly rather than via
                    # _owned_path_covers so a future rename of that self-
                    # append still fails this assertion instead of silently
                    # passing through the descendant-match fallback.
                    self.assertIn(".cep-install.json", owned_paths)
                    continue
                self.assertTrue(
                    _owned_path_covers(rel, owned_paths),
                    f"dry-run reported writing {rel!r} but no owned_paths entry covers it: "
                    f"{owned_paths!r}",
                )

    def test_full_install_owned_paths_cover_everything_the_dry_run_reports(self):
        self._assert_dry_run_paths_covered_by_owned_paths([self.init_flag], mode="full")

    def test_only_install_owned_paths_cover_everything_the_dry_run_reports(self):
        self._assert_dry_run_paths_covered_by_owned_paths(
            [self.only_flag, "ult-cep-wizard", self.init_flag],
            mode="only",
            only_skills=["ult-cep-wizard"],
        )


def _to_git_bash_path(win_path) -> str:
    """Converts a native Windows path (e.g. "C:\\foo\\bar") to the MSYS2
    mount-point form ("/c/foo/bar") Git Bash's own POSIX layer always
    accepts as an argument. Not every bash build on PATH can be assumed to
    understand a raw drive-letter path passed straight through as argv (the
    specific build matters here, not just "is bash present") — converting
    explicitly removes that assumption instead of depending on it. A no-op
    shape (backslashes flipped to forward slashes) on any path that isn't
    drive-letter-rooted, which also makes it harmless on POSIX."""
    p = str(win_path)
    if len(p) >= 2 and p[1] == ":" and p[0].isalpha():
        drive = p[0].lower()
        rest = p[2:].replace("\\", "/")
        return f"/{drive}{rest}"
    return p.replace("\\", "/")


@unittest.skipUnless(shutil.which("bash"), "bash not on PATH")
class TestInstallSh(_InstallScriptTestBase, unittest.TestCase):
    init_flag = "--init-project"
    dry_run_flag = "--dry-run"
    only_flag = "--only"
    runtime_flag = "--runtime"

    def _run(self, target, args):
        return subprocess.run(
            [
                "bash",
                _to_git_bash_path(INSTALL_SH),
                "--target",
                _to_git_bash_path(target),
                *args,
            ],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
        )


def _powershell_executable():
    return shutil.which("pwsh") or shutil.which("powershell")


@unittest.skipUnless(_powershell_executable(), "neither pwsh nor powershell on PATH")
class TestInstallPs1(_InstallScriptTestBase, unittest.TestCase):
    init_flag = "-InitProject"
    dry_run_flag = "-DryRun"
    only_flag = "-Only"
    runtime_flag = "-Runtime"

    def _run(self, target, args):
        exe = _powershell_executable()
        return subprocess.run(
            [exe, "-NoProfile", "-File", str(INSTALL_PS1), "-TargetPath", str(target), *args],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
        )


if __name__ == "__main__":
    unittest.main()
