"""Regression suite for onboarding_index.py (ult-onboarding-index).

Stdlib unittest only -- no pytest dependency, so this stays vendorable along
with onboarding_index.py itself. Run with:

    python -m unittest discover -s scripts/tests -v
"""

import json
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import onboarding_index as oi  # noqa: E402


def _write(path, content=""):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


class DiscoverTests(unittest.TestCase):
    def test_file_slot_present_and_absent(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            present = root / "cache" / "project-guidelines" / "COMPILED-GUIDELINES.md"
            _write(present, "# guidelines")
            absent = root / "cache" / "decision-ledger" / "DECISION-LEDGER.json"

            result = oi.discover(
                str(root),
                {"compiled_guidelines": str(present), "decision_ledger": str(absent)},
            )

            self.assertTrue(result["compiled_guidelines"]["exists"])
            self.assertFalse(result["decision_ledger"]["exists"])

    def test_directory_slot_requires_at_least_one_file(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            empty_dir = root / "contexts"
            empty_dir.mkdir()
            populated_dir = root / "outputs" / "plans"
            _write(populated_dir / "plan-1.md", "# plan")

            result = oi.discover(
                str(root),
                {"context_packages": str(empty_dir), "plans_output": str(populated_dir)},
            )

            self.assertFalse(result["context_packages"]["exists"])
            self.assertTrue(result["plans_output"]["exists"])

    def test_missing_repo_root_raises(self):
        with self.assertRaises(FileNotFoundError):
            oi.discover("/definitely/not/a/real/path", {})

    def test_how_l2_glob_finds_known_artifact_kinds(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            how_l2 = root / "inputs" / "org"
            _write(how_l2 / "CODING-STANDARDS.md", "# coding")
            _write(how_l2 / "interfaces" / "core-to-utils.md", "# interface")
            _write(how_l2 / "core" / "CONTEXT.md", "# module context")

            result = oi.discover(str(root), {}, how_l2_path=str(how_l2))

            found = result["how_l2"]["found"]
            self.assertIn("CODING-STANDARDS.md", found)
            self.assertNotIn("TESTING-GUIDELINES.md", found)
            self.assertIn("interfaces/core-to-utils.md", found)
            self.assertIn("core/CONTEXT.md", found)
            self.assertTrue(result["how_l2"]["exists"])

    def test_how_l2_absent_directory_reports_not_exists(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            result = oi.discover(str(root), {}, how_l2_path=str(root / "no-such-dir"))
            self.assertFalse(result["how_l2"]["exists"])
            self.assertEqual(result["how_l2"]["found"], [])


class SpliceMarkedBlockTests(unittest.TestCase):
    BEGIN = "<!-- BEGIN cep-onboarding-index (auto-generated by ult-onboarding-index, do not edit) -->"
    END = "<!-- END cep-onboarding-index -->"

    def test_file_does_not_exist_creates_it(self):
        new_text, action = oi.splice_marked_block(None, "hello", self.BEGIN, self.END)
        self.assertEqual(action, "created")
        self.assertIn(self.BEGIN, new_text)
        self.assertIn("hello", new_text)
        self.assertIn(self.END, new_text)

    def test_file_exists_without_markers_appends(self):
        existing = "# My repo\n\nSome hand-written notes.\n"
        new_text, action = oi.splice_marked_block(existing, "hello", self.BEGIN, self.END)
        self.assertEqual(action, "block-appended")
        self.assertTrue(new_text.startswith(existing))
        self.assertIn(self.BEGIN, new_text)
        self.assertIn("hello", new_text)

    def test_file_exists_with_markers_replaces_only_between_them(self):
        installer_block = (
            "<!-- BEGIN context-engineering-protocol SKILLS (auto-generated, do not edit) -->\n"
            "- some-skill\n"
            "<!-- END context-engineering-protocol SKILLS -->\n"
        )
        existing = (
            "# My repo\n\nHand-written prose.\n\n"
            + installer_block
            + "\n"
            + self.BEGIN + "\nold content\n" + self.END + "\n"
        )
        new_text, action = oi.splice_marked_block(existing, "new content", self.BEGIN, self.END)
        self.assertEqual(action, "block-replaced")
        self.assertIn("Hand-written prose.", new_text)
        self.assertIn(installer_block.strip(), new_text)
        self.assertIn("new content", new_text)
        self.assertNotIn("old content", new_text)

    def test_rerun_with_identical_content_is_idempotent(self):
        first_text, _ = oi.splice_marked_block(None, "hello", self.BEGIN, self.END)
        second_text, action = oi.splice_marked_block(first_text, "hello", self.BEGIN, self.END)
        self.assertEqual(action, "block-replaced")
        self.assertEqual(first_text, second_text)

    def test_only_one_marker_present_raises(self):
        existing = "# repo\n\n" + self.BEGIN + "\norphaned content\n"
        with self.assertRaises(ValueError):
            oi.splice_marked_block(existing, "new content", self.BEGIN, self.END)

    def test_never_touches_installer_marker_pair_text_itself(self):
        # Even when this skill's own markers are absent (append path), the
        # installer's differently-named marker pair must survive untouched.
        installer_block = (
            "<!-- BEGIN context-engineering-protocol SKILLS (auto-generated, do not edit) -->\n"
            "- some-skill\n"
            "<!-- END context-engineering-protocol SKILLS -->\n"
        )
        new_text, action = oi.splice_marked_block(installer_block, "hello", self.BEGIN, self.END)
        self.assertEqual(action, "block-appended")
        self.assertIn(installer_block.strip(), new_text)


class WriteStubTests(unittest.TestCase):
    def test_writes_when_absent(self):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / ".cursor" / "rules" / "onboarding.mdc"
            action = oi.write_stub(str(target), "stub content")
            self.assertEqual(action, "written")
            self.assertEqual(target.read_text(encoding="utf-8"), "stub content")

    def test_skips_when_present(self):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / ".cursor" / "rules" / "onboarding.mdc"
            _write(target, "pre-existing content")
            action = oi.write_stub(str(target), "stub content")
            self.assertEqual(action, "skipped")
            self.assertEqual(target.read_text(encoding="utf-8"), "pre-existing content")


class CliSmokeTests(unittest.TestCase):
    """Exercises main() end-to-end through the argparse layer, not just the pure functions."""

    def test_discover_cli_roundtrip(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            present = root / "cache" / "project-guidelines" / "COMPILED-GUIDELINES.md"
            _write(present, "# guidelines")
            slots_json = root / "slots.json"
            _write(slots_json, json.dumps({"compiled_guidelines": str(present)}))

            import io
            import contextlib

            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                rc = oi.main([
                    "discover", "--repo-root", str(root), "--slots-json", str(slots_json),
                ])
            self.assertEqual(rc, 0)
            result = json.loads(buf.getvalue())
            self.assertTrue(result["compiled_guidelines"]["exists"])

    def test_merge_block_cli_roundtrip(self):
        with tempfile.TemporaryDirectory() as d:
            root = Path(d)
            target = root / "AGENTS.md"
            block_file = root / "block.md"
            _write(block_file, "## CEP onboarding index\n\nsome content\n")

            import io
            import contextlib

            buf = io.StringIO()
            with contextlib.redirect_stdout(buf):
                rc = oi.main([
                    "merge-block", str(target), str(block_file),
                    "--begin-marker", SpliceMarkedBlockTests.BEGIN,
                    "--end-marker", SpliceMarkedBlockTests.END,
                ])
            self.assertEqual(rc, 0)
            result = json.loads(buf.getvalue())
            self.assertEqual(result["action"], "created")
            self.assertIn("some content", target.read_text(encoding="utf-8"))


if __name__ == "__main__":
    unittest.main()
