"""Regression suite for install.sh / install.ps1 (ROADMAP item 1, Phase 11).

Runs both installer scripts against real temporary target directories via
subprocess, exercising the same on-disk contract their own --help/synopsis
promises: copy the skill set (.github/skills/, .github/prompts/,
.cursor/rules/, AGENTS.md as a marked block) into --target/-TargetPath, and
under --init-project/-InitProject additionally scaffold context-config.yaml
and starter_kit/project_guidelines/.pointer.md.

Reuses generated_config_text() from test_generated_context_config.py rather
than re-deriving the substitution table a third time (install.sh and
install.ps1 each hardcode it once; this test is the independent witness that
both match the template).

Requires bash and one of {pwsh, powershell} on PATH; each installer's test
class is skipped (not failed) if its interpreter isn't available locally -
CI (ubuntu-latest) has both.

    python -m unittest discover -s scripts/tests -v
"""

import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from test_generated_context_config import generated_config_text  # noqa: E402

# .github/skills/ult-repo-layout/scripts/tests/ -> repo root
REPO_ROOT = Path(__file__).resolve().parents[5]
INSTALL_SH = REPO_ROOT / "install.sh"
INSTALL_PS1 = REPO_ROOT / "install.ps1"

LIBRARY_DIRS = [
    ".github/skills",
    ".github/prompts",
    ".cursor/rules",
]

BEGIN_MARKER = "<!-- BEGIN context-engineering-protocol SKILLS (auto-generated, do not edit) -->"
END_MARKER = "<!-- END context-engineering-protocol SKILLS -->"

POINTER_TEXT = """# project_guidelines — starter-kit drop-zone

This directory holds project-owned, human-curated material for `project_guidelines`.
Current template and README: `starter_kits/project_guidelines/` in the
skills library this project pulls from.

This file is regenerated by the installer's -InitProject/--init-project mode
and by `/ult-repo-layout init`/`reconcile` — do not edit it directly. Place
your own files alongside it; they are never touched.
"""


def _tree_files(root: Path):
    files = set()
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            rel = Path(dirpath, name).relative_to(root)
            files.add(str(rel).replace("\\", "/"))
    return files


def _assert_tree_matches(test, src: Path, dst: Path):
    test.assertTrue(dst.is_dir(), f"missing directory: {dst}")
    src_files = _tree_files(src)
    dst_files = _tree_files(dst)
    test.assertEqual(src_files, dst_files, f"file set mismatch between {src} and {dst}")
    for rel in src_files:
        test.assertEqual(
            (src / rel).read_bytes(),
            (dst / rel).read_bytes(),
            f"content mismatch: {rel}",
        )


class _InstallScriptTestBase:
    """Shared assertions across both installers; subclasses provide _run()."""

    def _run(self, target, args):
        raise NotImplementedError

    def test_plain_install_copies_library(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [])
            self.assertEqual(result.returncode, 0, result.stderr)
            for rel in LIBRARY_DIRS:
                _assert_tree_matches(self, REPO_ROOT / rel, target / rel)
            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertIn(BEGIN_MARKER, agents)
            self.assertIn(END_MARKER, agents)
            source_agents = (REPO_ROOT / "AGENTS.md").read_text(encoding="utf-8").strip()
            self.assertIn(source_agents, agents)
            self.assertFalse((target / "context-config.yaml").exists())
            self.assertFalse((target / "starter_kit").exists())

    def test_init_project_scaffolds_config_and_pointer(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.init_flag])
            self.assertEqual(result.returncode, 0, result.stderr)
            config_text = (target / "context-config.yaml").read_text(encoding="utf-8")
            self.assertEqual(config_text, generated_config_text())
            pointer_text = (
                target / "starter_kit" / "project_guidelines" / ".pointer.md"
            ).read_text(encoding="utf-8")
            self.assertEqual(pointer_text.strip(), POINTER_TEXT.strip())

    def test_rerun_is_idempotent(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            first = self._run(target, [self.init_flag])
            self.assertEqual(first.returncode, 0, first.stderr)

            # A hand-edited context-config.yaml must survive re-install:
            # it's project-owned, scaffold-once, never library-overwritten.
            (target / "context-config.yaml").write_text("# hand-edited\n", encoding="utf-8")

            second = self._run(target, [self.init_flag])
            self.assertEqual(second.returncode, 0, second.stderr)

            agents = (target / "AGENTS.md").read_text(encoding="utf-8")
            self.assertEqual(agents.count(BEGIN_MARKER), 1)
            self.assertEqual(
                (target / "context-config.yaml").read_text(encoding="utf-8"),
                "# hand-edited\n",
            )

    def test_dry_run_writes_nothing(self):
        with tempfile.TemporaryDirectory() as tmp:
            target = Path(tmp)
            result = self._run(target, [self.init_flag, self.dry_run_flag])
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(list(target.iterdir()), [])

    def test_missing_target_fails_clearly(self):
        with tempfile.TemporaryDirectory() as tmp:
            missing = Path(tmp) / "does-not-exist"
            result = self._run(missing, [])
            self.assertNotEqual(result.returncode, 0)
            self.assertIn("does not exist", result.stderr + result.stdout)


@unittest.skipUnless(shutil.which("bash"), "bash not on PATH")
class TestInstallSh(_InstallScriptTestBase, unittest.TestCase):
    init_flag = "--init-project"
    dry_run_flag = "--dry-run"

    def _run(self, target, args):
        return subprocess.run(
            ["bash", str(INSTALL_SH), "--target", str(target), *args],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
        )


def _powershell_executable():
    return shutil.which("pwsh") or shutil.which("powershell")


@unittest.skipUnless(_powershell_executable(), "neither pwsh nor powershell on PATH")
class TestInstallPs1(_InstallScriptTestBase, unittest.TestCase):
    init_flag = "-InitProject"
    dry_run_flag = "-DryRun"

    def _run(self, target, args):
        exe = _powershell_executable()
        return subprocess.run(
            [exe, "-NoProfile", "-File", str(INSTALL_PS1), "-TargetPath", str(target), *args],
            cwd=str(REPO_ROOT),
            capture_output=True,
            text=True,
        )


if __name__ == "__main__":
    unittest.main()
